// react/App.tsx
import { useState } from 'react'

function App() {
  const [count, setCount] = useState(0)

  return (
    <div style={{ textAlign: 'center', marginTop: '50px', fontFamily: 'sans-serif' }}>
      <h1>React + TypeScript</h1>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
      </div>
      <p>
        Check out the <a href="/">Vue App</a>
      </p>
    </div>
  )
}

export default App

// vue/App.vue
<template>
  <div style="text-align: center; margin-top: 50px; font-family: sans-serif;">
    <h1>Vue + JavaScript</h1>
    <div class="card">
      <button type="button" @click="count++">count is {{ count }}</button>
    </div>
    <p>
      Check out the <a href="/react">React App</a>
    </p>
  </div>
</template>

<script setup>
import { ref } from 'vue'
const count = ref(0)
</script>
